# Generated by Django 4.2.7 on 2025-12-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='episode_audio/'),
        ),
    ]
