# Generated by Django 5.0.2 on 2025-12-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_episode_audio_file_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='cover_image',
            field=models.ImageField(blank=True, default='covers/default_cover.jpg', null=True, upload_to='covers/'),
        ),
    ]
