# Generated by Django 5.0.2 on 2025-12-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_story_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='cover_image',
            field=models.ImageField(blank=True, default='media/covers/default_cover.jpg', null=True, upload_to='covers/'),
        ),
    ]
